language: php
php:
  - 7.2
services:
  - mysql
before_script:
  - composer install
script: ./vendor/bin/phpunit ./tests
deploy:
  provider: heroku
  app: curso-github-cefire-hermipp
  on: master
  skip_cleanup: true
  api_key:
    secure: UI+POITFL/PQc/VR7k1faVkpCKyLagjOhsI9bH8uzrb8cKFHEthhhEKPiLkmWyqycIpJlOR667YrR9mn48LTL047YuLcskeYjwo62cE+nhiLXUqE90rgihgCWHi36YbJRoQl1joTZR34ptDuE9IgoGfCBRZcg2+ANaQ5sbvHzgUrOVJBDTM6ba4BLtQIxfjKAWxbODfJadD/TZz4cjqAU9ffhPxhin0vAirAc/JVod0V8sxIn/mhd4ysJuBmA4f+u8SWgwelBkIdVYGOcwEDFI1nm6KYj0gKVX1xDbkA+NFSjU2Mmj/873lP9yAmQcOpO2Wq+BStN0qTcGLeVh6yoodf8X+r3Ft+Z6rpJCKvYMIbGfi1KWLRN+I2kNTrJGRtajDEsCs0H1sdQU3KYmCKOQNyIyrYt2K7xU43fOSZ5XjJIIdDibK6dlMJUcoWeIsQoDSaW6U7CPE6uLVWLfWaQ7R+vHnlWMLo+8i0DTZ2IZmFCgo79adcwjCmdPiUkDAFS0//Kg+X92vjjsfdaZOtX/0+pLOhelJww23dbe3TF9XneiXqpzBZtbfuoAs8/jl4jd9vZnLxRVCldRji2load7Vj+ixv9TejnobT2h0ObNtPqvAcBM0LklfYHbBfUgg8K+2EgTZ52FeVA5Ff+lBYKRCPiKwQX78362hkbwNh/8g=
    
